apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-deployment
  namespace: timex
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: data-ingestion
  template:
    metadata:
      labels:
        app: data-ingestion
    spec:
      shareProcessNamespace: true
      containers:
      - name: data-ingestion
        image: 485540626268.dkr.ecr.eu-west-1.amazonaws.com/dhiria_repo:ingestion_container
        imagePullPolicy: Always
        args: ["zk1.dhiria.com:9092,zk2.dhiria.com:9092,zk4.dhiria.com:9092", "ingestion"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: validation-deployment
  namespace: timex
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: validation
  template:
    metadata:
      labels:
        app: validation
    spec:
      shareProcessNamespace: true
      containers:
      - name: validation
        image: 485540626268.dkr.ecr.eu-west-1.amazonaws.com/dhiria_repo:validation_container
        imagePullPolicy: Always
        args: ["zk1.dhiria.com:9092,zk2.dhiria.com:9092,zk4.dhiria.com:9092", "validation"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prediction-deployment
  namespace: timex
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: prediction
  template:
    metadata:
      labels:
        app: prediction
    spec:
      shareProcessNamespace: true
      containers:
      - name: prediction
        image: 485540626268.dkr.ecr.eu-west-1.amazonaws.com/dhiria_repo:prediction_container
        imagePullPolicy: Always
        args: ["zk1.dhiria.com:9092,zk2.dhiria.com:9092,zk4.dhiria.com:9092", "prediction"]
